// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'extension-description'
  | 'pref-enable'
  | 'pref-help'
  | 'pref-input'
  | 'pref-title'
  | 'startup-begin'
  | 'startup-finish'
  | 'week-plan-column-doing'
  | 'week-plan-column-done'
  | 'week-plan-column-planning'
  | 'week-plan-column-todo'
  | 'week-plan-menu'
  | 'week-plan-tab'
  | 'week-plan-title'
  | 'week-plan-toolbar-search'
  | 'week-plan-toolbar-stats';
